codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

parsers:
  jacoco:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "src/test/**"
  - "**/*Test.java"
  - "**/*Tests.java"
  - "**/model/**"  # Exclude entity classes

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true